#!/bin/bash
# Claude Code Adapter — Clean Script
# Removes all files generated by the Claude Code adapter from output/claude/
#
# Usage: bash adapters/claude/clean.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT_DIR="$PROJECT_ROOT/output/claude"

source "$PROJECT_ROOT/.ai/scripts/_lib.sh"

echo -e "${BLUE}=== Claude Code Adapter Clean ===${NC}"
echo ""

if [ -d "$OUTPUT_DIR" ]; then
    rm -rf "$OUTPUT_DIR"
    echo -e "${GREEN}✓${NC} Removed output/claude/"
    echo ""
    echo -e "${GREEN}=== Claude Code adapter output removed ===${NC}"
else
    echo -e "${YELLOW}Nothing to clean — output/claude/ not found.${NC}"
fi
