#!/bin/bash
# Life Systems Engineering — Setup Script
# =========================================
# Run this BEFORE installing any adapter.
# It configures the journal path and creates the initial journal structure.
#
# Usage:
#   bash .ai/scripts/setup-life-engineering.sh
#   bash .ai/scripts/setup-life-engineering.sh --path /absolute/path/to/life-journal
#
# Then:
#   bash adapters/opencode/install.sh   # or claude, cursor, aider, etc.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG_FILE="$PROJECT_ROOT/.ai/life-config.yaml"
LIB_SCRIPT="$PROJECT_ROOT/.ai/scripts/_lib.sh"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Parse --path argument
if [[ "${1:-}" == "--path" && -n "${2:-}" ]]; then
    JOURNAL_PATH="${2//\\//}"  # Normalize backslashes to forward slashes
elif [[ "${1:-}" == "--path" ]]; then
    echo -e "${RED}ERROR: --path requires an argument${NC}"
    exit 1
fi

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Life Systems Engineering Setup${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Step 1: Get or validate journal path
if [[ -z "${JOURNAL_PATH:-}" ]]; then
    echo -e "${YELLOW}No journal path provided.${NC}"
    echo "The life-journal is where all your daily data lives: metrics, logs, decisions, incidents."
    echo "It should be a git repository (recommended: private GitHub repo for multi-device sync)."
    echo ""
    echo -e "Enter the absolute path for your life-journal (e.g., ${BLUE}/home/you/life-journal${NC}):"
    read -r JOURNAL_PATH
    JOURNAL_PATH="${JOURNAL_PATH//\\//}"  # Normalize backslashes
fi

# Validate path is absolute
if [[ "$JOURNAL_PATH" != /* && "$JOURNAL_PATH" != [A-Za-z]:/* ]]; then
    echo -e "${RED}ERROR: Path must be absolute (e.g., /home/you/life-journal or C:/Users/you/life-journal)${NC}"
    exit 1
fi

echo ""
echo -e "Journal path: ${BLUE}$JOURNAL_PATH${NC}"
echo ""

# Step 2: Write config file
echo -e "${BLUE}Writing config to $CONFIG_FILE${NC}"
cat > "$CONFIG_FILE" << CONFIGEOF
# Life Systems Engineering — Journal Configuration
# =================================================
# Auto-generated by setup-life-engineering.sh
# Do not edit manually — re-run setup to change path.
# =================================================

journal_path: "$JOURNAL_PATH"
git_auto: true
git_auto_push: true
CONFIGEOF
echo -e "${GREEN}✓${NC} Config written"

# Step 3: Create journal directory structure if it doesn't exist
echo -e "${BLUE}Creating journal directory structure...${NC}"
mkdir -p "$JOURNAL_PATH/daily"
mkdir -p "$JOURNAL_PATH/time-series"
mkdir -p "$JOURNAL_PATH/events"
mkdir -p "$JOURNAL_PATH/incidents"
mkdir -p "$JOURNAL_PATH/decisions"
mkdir -p "$JOURNAL_PATH/weekly"
mkdir -p "$JOURNAL_PATH/meta"
echo -e "${GREEN}✓${NC} Directories created"

# Step 4: Create CSV headers
echo -e "${BLUE}Creating time-series CSV files...${NC}"
if [ ! -f "$JOURNAL_PATH/time-series/energy.csv" ]; then
    echo "date,period,level,activity,notes" > "$JOURNAL_PATH/time-series/energy.csv"
    echo "date,session_id,score,duration_min,distractions,notes" > "$JOURNAL_PATH/time-series/focus.csv"
    echo "date,timestamp,emotion,intensity,category,trigger,regulation,effectiveness" > "$JOURNAL_PATH/time-series/mood.csv"
    echo "date,hours,quality,bedtime,waketime,notes" > "$JOURNAL_PATH/time-series/sleep.csv"
    echo "date,timestamp,emotion,intensity,trigger,context,narrative,urge,deviation_type,regulation,effectiveness" > "$JOURNAL_PATH/events/triggers.csv"
    echo "date,distortion_type,original_thought,severity,reframe" > "$JOURNAL_PATH/events/distortions.csv"
    echo -e "${GREEN}✓${NC} CSV headers created"
else
    echo -e "${GREEN}✓${NC} CSV files already exist, skipping"
fi

# Step 5: Create baselines.json
if [ ! -f "$JOURNAL_PATH/meta/baselines.json" ]; then
    cat > "$JOURNAL_PATH/meta/baselines.json" << 'BASELINESEOF'
{
  "energy": { "avg": null, "stddev": null, "min": null, "max": null, "data_points": 0, "last_computed": null },
  "focus": { "avg": null, "stddev": null, "min": null, "max": null, "data_points": 0, "last_computed": null },
  "mood_intensity": { "avg": null, "stddev": null, "min": null, "max": null, "data_points": 0, "last_computed": null },
  "sleep_quality": { "avg": null, "stddev": null, "min": null, "max": null, "data_points": 0, "last_computed": null },
  "sleep_hours": { "avg": null, "stddev": null, "min": null, "max": null, "data_points": 0, "last_computed": null },
  "emotional": { "common_emotions": [], "common_triggers": [], "emotional_volatility": null, "total_events": 0, "last_computed": null },
  "cognitive": { "common_distortions": [], "total_scans": 0, "last_computed": null },
  "anomaly_threshold_stddevs": 2.0,
  "data_points": 0,
  "last_computed": null
}
BASELINESEOF
    echo -e "${GREEN}✓${NC} baselines.json created"
else
    echo -e "${GREEN}✓${NC} baselines.json already exists, skipping"
fi

# Step 6: Create journal README
if [ ! -f "$JOURNAL_PATH/README.md" ]; then
    cat > "$JOURNAL_PATH/README.md" << 'READMEEOF'
# Life Systems Engineering Journal

Persistent data store for the Life Systems Engineering daily practices.
Auto-generated by setup-life-engineering.sh
READMEEOF
    echo -e "${GREEN}✓${NC} README.md created"
fi

# Step 7: Create .gitignore
if [ ! -f "$JOURNAL_PATH/.gitignore" ]; then
    cat > "$JOURNAL_PATH/.gitignore" << 'GITIGNOREEOF'
# OS files
.DS_Store
Thumbs.db
desktop.ini
# Editor files
*.swp
*.swo
*~
GITIGNOREEOF
    echo -e "${GREEN}✓${NC} .gitignore created"
fi

# Step 8: Init git repo
if [ ! -d "$JOURNAL_PATH/.git" ]; then
    echo -e "${BLUE}Initializing git repository...${NC}"
    cd "$JOURNAL_PATH"
    git init
    git add -A
    git commit -m "init: life-journal structure"
    echo -e "${GREEN}✓${NC} Git repo initialized"
else
    echo -e "${GREEN}✓${NC} Git repo already exists"
fi

# Step 9: Summary
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Setup Complete${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "  Config:     $CONFIG_FILE"
echo "  Journal:    $JOURNAL_PATH"
echo ""
echo "Next steps:"
echo "  1. Create a private GitHub repo named 'life-journal'"
echo "  2. cd $JOURNAL_PATH"
echo "  3. git remote add origin https://github.com/YOUR_USERNAME/life-journal.git"
echo "  4. git push -u origin master"
echo "  5. Install your adapter:"
echo "     - bash adapters/opencode/install.sh"
echo "     - bash adapters/claude/install.sh"
echo "     - etc."
echo ""
echo -e "${YELLOW}IMPORTANT: All workflows now read journal_path from config.yaml${NC}"
echo -e "${YELLOW}Do NOT hardcode paths in workflows anymore.${NC}"
echo ""
