#!/bin/bash
# Codex Adapter — Clean Script
# Removes all files generated by the Codex adapter from output/codex/
#
# Usage: bash adapters/codex/clean.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT_DIR="$PROJECT_ROOT/output/codex"

source "$PROJECT_ROOT/.ai/scripts/_lib.sh"

echo -e "${BLUE}=== Codex Adapter Clean ===${NC}"
echo ""

if [ -d "$OUTPUT_DIR" ]; then
    rm -rf "$OUTPUT_DIR"
    echo -e "${GREEN}✓${NC} Removed output/codex/"
    echo ""
    echo -e "${GREEN}=== Codex adapter output removed ===${NC}"
else
    echo -e "${YELLOW}Nothing to clean — output/codex/ not found.${NC}"
fi
