#!/bin/bash
# OpenCode Adapter — Clean Script
# Removes files generated by the OpenCode adapter from output/opencode/
#
# Usage: bash adapters/opencode/clean.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT_DIR="$PROJECT_ROOT/output/opencode"

source "$PROJECT_ROOT/.ai/scripts/_lib.sh"

echo -e "${BLUE}=== OpenCode Adapter Clean ===${NC}"
echo ""

if [ -d "$OUTPUT_DIR" ]; then
    rm -rf "$OUTPUT_DIR"
    echo -e "${GREEN}✓${NC} Removed output/opencode/"
    echo ""
    echo -e "${GREEN}=== OpenCode adapter output removed ===${NC}"
else
    echo -e "${YELLOW}Nothing to clean — output/opencode/ not found.${NC}"
fi
