#!/bin/bash
# OpenCode Adapter — Clean Script
# Removes files generated by the OpenCode adapter
#
# Usage: bash adapters/opencode/clean.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

source "$PROJECT_ROOT/.ai/scripts/_lib.sh"

echo -e "${BLUE}=== OpenCode Adapter Clean ===${NC}"
echo ""

REMOVED=0

# Remove .opencode/ directory
if [ -d "$PROJECT_ROOT/.opencode" ]; then
    rm -rf "$PROJECT_ROOT/.opencode"
    echo -e "${GREEN}✓${NC} Removed .opencode/ directory"
    REMOVED=$((REMOVED + 1))
fi

# Remove AGENTS.md if it was generated by this adapter
# Note: We check if it contains the OpenCode-specific header
if [ -f "$PROJECT_ROOT/AGENTS.md" ]; then
    if grep -q "<!-- Auto-generated from .ai/context/ by OpenCode adapter -->" "$PROJECT_ROOT/AGENTS.md" 2>/dev/null; then
        rm -f "$PROJECT_ROOT/AGENTS.md"
        echo -e "${GREEN}✓${NC} Removed AGENTS.md (OpenCode-generated)"
        REMOVED=$((REMOVED + 1))
    else
        echo -e "${YELLOW}⚠${NC} AGENTS.md exists but doesn't appear to be OpenCode-generated"
        echo "   (missing '<!-- Auto-generated from .ai/context/ by OpenCode adapter -->' comment)"
    fi
fi

# Remove opencode.json if it exists
if [ -f "$PROJECT_ROOT/opencode.json" ]; then
    rm -f "$PROJECT_ROOT/opencode.json"
    echo -e "${GREEN}✓${NC} Removed opencode.json"
    REMOVED=$((REMOVED + 1))
fi

echo ""
if [ $REMOVED -eq 0 ]; then
    echo -e "${YELLOW}Nothing to clean — OpenCode adapter output not found.${NC}"
else
    echo -e "${GREEN}=== OpenCode adapter output removed ($REMOVED items) ===${NC}"
fi