#!/bin/bash
# Cursor Adapter — Clean Script
# Removes all files generated by the Cursor adapter
#
# Usage: bash adapters/cursor/clean.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

source "$PROJECT_ROOT/.ai/scripts/_lib.sh"

echo -e "${BLUE}=== Cursor Adapter Clean ===${NC}"
echo ""

REMOVED=0

# Remove .cursorrules
if [ -f "$PROJECT_ROOT/.cursorrules" ]; then
    rm "$PROJECT_ROOT/.cursorrules"
    echo -e "${GREEN}✓${NC} Removed .cursorrules"
    REMOVED=$((REMOVED + 1))
fi

# Remove .cursor/ directory (created for MCP config)
if [ -d "$PROJECT_ROOT/.cursor" ]; then
    rm -rf "$PROJECT_ROOT/.cursor"
    echo -e "${GREEN}✓${NC} Removed .cursor/"
    REMOVED=$((REMOVED + 1))
fi

echo ""
if [ $REMOVED -eq 0 ]; then
    echo -e "${YELLOW}Nothing to clean — Cursor adapter output not found.${NC}"
else
    echo -e "${GREEN}=== Cursor adapter output removed ($REMOVED items) ===${NC}"
fi
