#!/bin/bash
# Cursor Adapter — Clean Script
# Removes all files generated by the Cursor adapter from output/cursor/
#
# Usage: bash adapters/cursor/clean.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT_DIR="$PROJECT_ROOT/output/cursor"

source "$PROJECT_ROOT/.ai/scripts/_lib.sh"

echo -e "${BLUE}=== Cursor Adapter Clean ===${NC}"
echo ""

if [ -d "$OUTPUT_DIR" ]; then
    rm -rf "$OUTPUT_DIR"
    echo -e "${GREEN}✓${NC} Removed output/cursor/"
    echo ""
    echo -e "${GREEN}=== Cursor adapter output removed ===${NC}"
else
    echo -e "${YELLOW}Nothing to clean — output/cursor/ not found.${NC}"
fi
