#!/bin/bash
# Aider Adapter — Clean Script
# Removes all files generated by the Aider adapter from output/aider/
#
# Usage: bash adapters/aider/clean.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT_DIR="$PROJECT_ROOT/output/aider"

source "$PROJECT_ROOT/.ai/scripts/_lib.sh"

echo -e "${BLUE}=== Aider Adapter Clean ===${NC}"
echo ""

if [ -d "$OUTPUT_DIR" ]; then
    rm -rf "$OUTPUT_DIR"
    echo -e "${GREEN}✓${NC} Removed output/aider/"
    echo ""
    echo -e "${GREEN}=== Aider adapter output removed ===${NC}"
else
    echo -e "${YELLOW}Nothing to clean — output/aider/ not found.${NC}"
fi
