#!/bin/bash
# Antigravity Adapter — Clean Script
# Removes all files generated by the Antigravity adapter
#
# Usage: bash adapters/antigravity/clean.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

source "$PROJECT_ROOT/.ai/scripts/_lib.sh"

echo -e "${BLUE}=== Antigravity Adapter Clean ===${NC}"
echo ""

REMOVED=0

# Remove .agent/ directory
if [ -d "$PROJECT_ROOT/.agent" ]; then
    rm -rf "$PROJECT_ROOT/.agent"
    echo -e "${GREEN}✓${NC} Removed .agent/"
    REMOVED=$((REMOVED + 1))
fi

# Remove .gemini/ directory
if [ -d "$PROJECT_ROOT/.gemini" ]; then
    rm -rf "$PROJECT_ROOT/.gemini"
    echo -e "${GREEN}✓${NC} Removed .gemini/"
    REMOVED=$((REMOVED + 1))
fi

# Remove .agent/config.json if it exists
if [ -f "$PROJECT_ROOT/.agent/config.json" ]; then
    rm -f "$PROJECT_ROOT/.agent/config.json"
    echo -e "${GREEN}✓${NC} Removed .agent/config.json"
    REMOVED=$((REMOVED + 1))
fi

echo ""
if [ $REMOVED -eq 0 ]; then
    echo -e "${YELLOW}Nothing to clean — Antigravity adapter output not found.${NC}"
else
    echo -e "${GREEN}=== Antigravity adapter output removed ($REMOVED items) ===${NC}"
fi
