#!/bin/bash
# Antigravity Adapter — Clean Script
# Removes all files generated by the Antigravity adapter from output/antigravity/
#
# Usage: bash adapters/antigravity/clean.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT_DIR="$PROJECT_ROOT/output/antigravity"

source "$PROJECT_ROOT/.ai/scripts/_lib.sh"

echo -e "${BLUE}=== Antigravity Adapter Clean ===${NC}"
echo ""

if [ -d "$OUTPUT_DIR" ]; then
    rm -rf "$OUTPUT_DIR"
    echo -e "${GREEN}✓${NC} Removed output/antigravity/"
    echo ""
    echo -e "${GREEN}=== Antigravity adapter output removed ===${NC}"
else
    echo -e "${YELLOW}Nothing to clean — output/antigravity/ not found.${NC}"
fi
